# Generated by Django 3.2 on 2021-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noungenderguess_revlog',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='noungenderguess_revlog',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_revlog',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_revlog',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
