# Generated by Django 3.2 on 2021-05-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPronoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun_de', models.CharField(max_length=20)),
                ('pronoun_en', models.CharField(max_length=20)),
                ('case', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
