# Generated by Django 3.2 on 2021-05-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_personalpronoun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpronoun',
            name='gender',
        ),
        migrations.AddField(
            model_name='personalpronoun',
            name='nom_pronoun_de',
            field=models.CharField(default='temp', max_length=10),
        ),
        migrations.AddField(
            model_name='personalpronoun',
            name='order',
            field=models.CharField(default='temp', max_length=10),
        ),
    ]
