# Generated by Django 3.2 on 2021-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20210501_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='noun_en_pl',
            field=models.CharField(default='temp', max_length=20),
        ),
    ]
