# Generated by Django 3.2 on 2021-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20210511_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_de',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_en',
            field=models.CharField(max_length=20),
        ),
    ]
