# Generated by Django 3.2 on 2021-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_noun_noun_en_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_de',
            field=models.CharField(max_length=10),
        ),
    ]
