# Generated by Django 3.2 on 2021-05-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20210511_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noun',
            old_name='noun_de_pl',
            new_name='word_de_pl',
        ),
        migrations.RenameField(
            model_name='noun',
            old_name='noun_en_pl',
            new_name='word_en_pl',
        ),
    ]
