# Generated by Django 3.2 on 2021-05-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_article_article_de'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('case', 'gender', 'definite')},
        ),
    ]
