# Generated by Django 3.2 on 2021-05-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20210511_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalPronoun_RevLog',
        ),
    ]
