# Generated by Django 3.2 on 2021-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='infinitive_de',
            field=models.CharField(default='temp', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='verb',
            unique_together={('infinitive_de', 'mood', 'tense', 'subject')},
        ),
    ]
