# Generated by Django 3.2 on 2021-05-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_delete_personalpronoun_revlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noungenderguess_revlog',
            old_name='noun',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='nounpluralizationguess_revlog',
            old_name='noun',
            new_name='pos',
        ),
    ]
