# Generated by Django 3.2 on 2021-05-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20210502_0048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalpronoun',
            unique_together={('nom_pronoun_de', 'case')},
        ),
    ]
