# Generated by Django 3.2 on 2021-05-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_personalpronoun_revlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_studied_utc', models.DateTimeField(auto_now_add=True)),
                ('ease', models.FloatField(default=1.0)),
                ('interval', models.FloatField(default=0.25)),
            ],
        ),
    ]
