# Generated by Django 3.2 on 2021-05-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_cardscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardScore',
        ),
    ]
