# Generated by Django 3.2 on 2021-05-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_personalpronoun_verb_article_noun_revlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalPronoun_Verb_Article_Noun',
            new_name='PersonalPronoun_Verb_Article_Noun_RevLog',
        ),
    ]
