# Generated by Django 3.2 on 2021-05-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_noungenderscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NounGenderScore',
            new_name='NounGenderGuess_Score',
        ),
    ]
