# Generated by Django 3.2 on 2021-05-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_noungenderguess_revlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpronoun',
            name='order',
        ),
        migrations.AlterField(
            model_name='noun',
            name='noun_en_pl',
            field=models.CharField(default='temporary', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalpronoun',
            name='nom_pronoun_de',
            field=models.CharField(default='temporary', max_length=10),
        ),
        migrations.AlterField(
            model_name='verb',
            name='infinitive_de',
            field=models.CharField(default='temporary', max_length=20),
        ),
    ]
