# Generated by Django 3.2 on 2021-05-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_auto_20210514_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noungenderguess_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revlogs', to='flashcards.noungenderguess_score'),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revlogs', to='flashcards.nounpluralizationguess_score'),
        ),
        migrations.AlterField(
            model_name='personalpronoun_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revlogs', to='flashcards.personalpronoun_score'),
        ),
    ]
