# Generated by Django 3.2 on 2021-05-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_personalpronoun_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalpronoun',
            name='person',
            field=models.IntegerField(),
        ),
    ]
