# Generated by Django 3.2 on 2021-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_auto_20210515_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='noungenderguess_card',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nounpluralizationguess_card',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalpronoun_card',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
