# Generated by Django 3.2 on 2021-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_alter_personalpronoun_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpronoun',
            name='is_plural',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='personalpronoun',
            unique_together={('nom_pronoun_de', 'case', 'person')},
        ),
    ]
