# Generated by Django 3.2 on 2021-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0018_auto_20210516_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalpronoun',
            old_name='person',
            new_name='person_order',
        ),
        migrations.AddField(
            model_name='personalpronoun',
            name='plural_order',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='personalpronoun',
            unique_together={('plural_order', 'person_order', 'case')},
        ),
        migrations.RemoveField(
            model_name='personalpronoun',
            name='is_plural',
        ),
        migrations.RemoveField(
            model_name='personalpronoun',
            name='nom_pronoun_de',
        ),
    ]
