# Generated by Django 3.2 on 2021-05-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0019_auto_20210516_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalpronoun',
            unique_together={('plural_order', 'person_order', 'case', 'word_de')},
        ),
    ]
