# Generated by Django 3.2 on 2021-05-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0019_alter_personalpronoun_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NounPluralizationGuess_RevLog',
            fields=[
                ('revlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flashcards.revlog')),
                ('noun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.noun')),
            ],
            bases=('flashcards.revlog',),
        ),
    ]
