# Generated by Django 3.2 on 2021-05-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_alter_personalpronoun_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalpronoun',
            unique_together={('plural_order', 'person_order', 'case', 'word_en')},
        ),
    ]
