# Generated by Django 3.2 on 2021-05-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_nounpluralizationguess_revlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalPronoun_Verb_Article_Noun_RevLog',
        ),
    ]
