# Generated by Django 3.2 on 2021-05-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0021_alter_personalpronoun_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_studied_utc', models.DateTimeField(auto_now_add=True)),
                ('num_repetitions', models.IntegerField(default=0)),
                ('ease', models.FloatField(default=1.0)),
                ('interval', models.FloatField(default=0.25)),
                ('pos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
