# Generated by Django 3.2 on 2021-05-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0022_article_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_RevLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revlogs', to='flashcards.article_card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
