# Generated by Django 3.2 on 2021-05-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0023_article_revlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noun',
            unique_together={('word_en', 'word_de')},
        ),
    ]
