# Generated by Django 3.2 on 2021-05-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0025_noundeenmeaning_card_nounendemeaning_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='pluralization_model',
        ),
    ]
