# Generated by Django 3.2 on 2021-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0026_remove_noun_pluralization_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_de',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_en',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_de',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_en',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personalpronoun',
            name='word_de',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personalpronoun',
            name='word_en',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word_de',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word_en',
            field=models.CharField(max_length=40),
        ),
    ]
