# Generated by Django 3.2 on 2021-05-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0028_auto_20210524_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_de',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_en',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_de',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_de_pl',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_en',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word_en_pl',
            field=models.CharField(default='temporary', max_length=110),
        ),
        migrations.AlterField(
            model_name='personalpronoun',
            name='word_de',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='personalpronoun',
            name='word_en',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word_de',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word_en',
            field=models.CharField(max_length=110),
        ),
    ]
