# Generated by Django 3.2 on 2021-05-24 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0029_auto_20210524_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.article'),
        ),
        migrations.AlterField(
            model_name='noundeenmeaning_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.noun'),
        ),
        migrations.AlterField(
            model_name='nounendemeaning_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.noun'),
        ),
        migrations.AlterField(
            model_name='noungenderguess_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.noun'),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.noun'),
        ),
        migrations.AlterField(
            model_name='personalpronoun_card',
            name='pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.personalpronoun'),
        ),
    ]
