# Generated by Django 3.2 on 2021-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0031_noundeenmeaning_revlog_nounendemeaning_revlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noundeenmeaning_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nounendemeaning_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noungenderguess_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personalpronoun_card',
            name='last_studied_utc',
            field=models.DateField(auto_now_add=True),
        ),
    ]
