# Generated by Django 3.2 on 2021-05-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0032_auto_20210524_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
        migrations.RenameField(
            model_name='noundeenmeaning_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
        migrations.RenameField(
            model_name='nounendemeaning_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
        migrations.RenameField(
            model_name='noungenderguess_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
        migrations.RenameField(
            model_name='nounpluralizationguess_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
        migrations.RenameField(
            model_name='personalpronoun_card',
            old_name='last_studied_utc',
            new_name='last_studied_date',
        ),
    ]
