# Generated by Django 3.2 on 2021-05-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0033_auto_20210524_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.article_card'),
        ),
        migrations.AlterField(
            model_name='noundeenmeaning_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.noundeenmeaning_card'),
        ),
        migrations.AlterField(
            model_name='nounendemeaning_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.nounendemeaning_card'),
        ),
        migrations.AlterField(
            model_name='noungenderguess_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.noungenderguess_card'),
        ),
        migrations.AlterField(
            model_name='nounpluralizationguess_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.nounpluralizationguess_card'),
        ),
        migrations.AlterField(
            model_name='personalpronoun_revlog',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revlogs', to='flashcards.personalpronoun_card'),
        ),
    ]
