# Generated by Django 3.2 on 2021-07-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0039_infinitiveverbdeenmeaning_card_infinitiveverbdeenmeaning_revlog_infinitiveverbendemeaning_card_infin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infinitiveverb',
            unique_together={('word_de', 'word_en')},
        ),
    ]
