# Generated by Django 3.2 on 2021-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0040_alter_infinitiveverb_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpronoun',
            name='nominativ',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
